exports.arrayOfStores = [
  // {
  //   storeName: "priceoye.pk",
  //   mainContainer: ".productBox.b-productBox",
  //   DeliveryCharges: "Free",
  //   imgTag: "amp-img",
  //   detailBoxClasses: {
  //     proDetailBox: "#product-summary",
  //     name: "h3",
  //     price: ".summary-price.text-black.price-size-lg.bold",
  //     stock: ".summary-price.text-black.bold.stock-status",
  //     rating: ".semi-bold.rating-points",
  //   },
  //   arrayOfRoutes: [
  //     { routes: "mobiles/apple", category: "Mobiles" },
  //     { routes: "mobiles/samsung", category: "Mobiles" },
  //     // { routes: "mobiles/oppo", category: "Mobiles" },
  //     // { routes: "mobiles/realme", category: "Mobiles" },
  //     // { routes: "mobiles/infinix", category: "Mobiles" },
  //     // { routes: "mobiles/tecno", category: "Mobiles" },
  //     // { routes: "mobiles/vivo", category: "Mobiles" },
  //     // { routes: "mobiles/xiaomi", category: "Mobiles" },
  //     // { routes: "tablets/apple", category: "Tablets" },
  //     // { routes: "tablets/samsung", category: "Tablets" },
  //     // { routes: "tablets/huawei", category: "Tablets" },
  //     // { routes: "tablets/deny", category: "Tablets" },
  //     // { routes: "smart-watches/apple", category: "Smart-Watches" },
  //     // { routes: "smart-watches/huawei", category: "Smart-Watches" },
  //     // { routes: "smart-watches/samsung", category: "Smart-Watches" },
  //     // { routes: "smart-watches/huawei", category: "Smart-Watches" },
  //     // { routes: "smart-watches/xiaomi", category: "Smart-Watches" },
  //     // { routes: "wireless-earbuds/anker", category: "Wireless-Earbuds" },
  //     // { routes: "wireless-earbuds/baseus", category: "Wireless-Earbuds" },
  //     // { routes: "wireless-earbuds/ronin", category: "Wireless-Earbuds" },
  //     // { routes: "wireless-earbuds/apple", category: "Wireless-Earbuds" },
  //     // { routes: "wireless-earbuds/huawei", category: "Wireless-Earbuds" },
  //     // { routes: "wireless-earbuds/samsung", category: "Wireless-Earbuds" },
  //     // { routes: "wireless-earbuds/huawei", category: "Wireless-Earbuds" },
  //     // { routes: "wireless-earbuds/xiaomi", category: "Wireless-Earbuds" },
  //     // { routes: "laptops/apple", category: "Laptops" },
  //     // { routes: "laptops/hp", category: "Laptops" },
  //     // { routes: "laptops/dell", category: "Laptops" },
  //     // { routes: "laptops/lenovo", category: "Laptops" },
  //   ],
  // },
  // {
  //   storeName: "qmart.pk",
  //   // mainContainer: ".main-products.product-grid",
  //   mainContainer: ".product-layout",
  //   DeliveryCharges: "500",
  //   imgTag: "img",
  //   // detailBoxClasses: {
  //   //   proDetailBox: "#product-summary",
  //   //   name: "h3",
  //   //   price: ".summary-price.text-black.price-size-lg.bold",
  //   //   stock: ".summary-price.text-black.bold.stock-status",
  //   //   rating: ".semi-bold.rating-points",
  //   // },
  //   arrayOfRoutes: [
  //     // {
  //     //   routes: "iPhone-price-in-pakistan?limit=100",
  //     //   category: "Mobiles",
  //     //   brand: "Apple",
  //     // },
  //     // {
  //     //   routes: "apple-iphone-13-price-in-pakistan",
  //     //   category: "Mobiles",
  //     //   brand: "Apple",
  //     // },
  //     //   {
  //     //     routes: "macbook-air?limit=100",
  //     //     category: "Laptops",
  //     //     brand: "Apple",
  //     //   },
  //     //   {
  //     //     routes: "apple-series-8-online-in-pakistan",
  //     //     category: "Smart-Watches",
  //     //     brand: "Apple",
  //     //   },
  //     //   {
  //     //     routes: "mi-smart-watches?limit=100",
  //     //     category: "Smart-Watches",
  //     //     brand: "Xiaomi",
  //     //   },
  //     //   {
  //     //     routes: "samsung-watch?limit=100",
  //     //     category: "Smart-Watches",
  //     //     brand: "Samsung",
  //     //   },
  //     //   {
  //     //     routes: "apple-bluetooth?limit=100",
  //     //     category: "Wireless-Earbuds",
  //     //     brand: "Apple",
  //     //   },
  //     //   {
  //     //     routes: "apple-tv",
  //     //     category: "TV-&-Home-Appliances",
  //     //     brand: "Apple",
  //     //   },
  //     {
  //       routes: "Samsung-mobiles-price-in-pakistan?limit=100",
  //       category: "Mobiles",
  //       brand: "Samsung",
  //     },
  //     //   {
  //     //     routes: "samsung-tablets?limit=100",
  //     //     category: "Tablets",
  //     //     brand: "Samsung",
  //     //   },
  //     //   {
  //     //     routes: "Realme-mobiles-price-in-pakistan?limit=100",
  //     //     category: "Mobiles",
  //     //     brand: "Realme",
  //     //   },
  //     //   {
  //     //     routes: "Infinix-mobiles-price-in-pakistan?limit=100",
  //     //     category: "Mobiles",
  //     //     brand: "Infinix",
  //     //   },
  //     //   {
  //     //     routes: "Oppo-mobiles-price-in-pakistan?limit=100",
  //     //     category: "Mobiles",
  //     //     brand: "Oppo",
  //     //   },
  //     //   {
  //     //     routes: "Tecno-mobiles-price-in-pakistan?limit=100",
  //     //     category: "Mobiles",
  //     //     brand: "Tecno",
  //     //   },
  //     //   {
  //     //     routes: "Vivo-mobiles-price-in-pakistan?limit=100",
  //     //     category: "Mobiles",
  //     //     brand: "Vivo",
  //     //   },
  //     //   {
  //     //     routes: "Nokia-mobiles-price-in-pakistan?limit=100",
  //     //     category: "Mobiles",
  //     //     brand: "Nokia",
  //     //   },
  //     //   {
  //     //     routes: "Mi-Xiaomi-mobile-price-in-pakistan?limit=100",
  //     //     category: "Mobiles",
  //     //     brand: "Xiaomi",
  //     //   },
  //     //   {
  //     //     routes: "Apple-iPads-Prices-in-Pakistan?limit=100",
  //     //     category: "Mobiles",
  //     //     brand: "Apple",
  //     //   },
  //   ],
  // },
  {
    storeName: "mobile-phone.pk",
    // mainContainer: ".main-products.product-grid",
    mainContainer: ".product-layout",
    DeliveryCharges: "0 to 500",
    imgTag: "img",
    // detailBoxClasses: {
    //   proDetailBox: "#product-summary",
    //   name: "h3",
    //   price: ".summary-price.text-black.price-size-lg.bold",
    //   stock: ".summary-price.text-black.bold.stock-status",
    //   rating: ".semi-bold.rating-points",
    // },
    arrayOfRoutes: [
      // {
      //   routes: "iPhone-price-in-pakistan?limit=100",
      //   category: "Mobiles",
      //   brand: "Apple",
      // },
      // {
      //   routes: "apple-iphone-13-price-in-pakistan",
      //   category: "Mobiles",
      //   brand: "Apple",
      // },
      //   {
      //     routes: "macbook-air?limit=100",
      //     category: "Laptops",
      //     brand: "Apple",
      //   },
      //   {
      //     routes: "apple-series-8-online-in-pakistan",
      //     category: "Smart-Watches",
      //     brand: "Apple",
      //   },
      //   {
      //     routes: "mi-smart-watches?limit=100",
      //     category: "Smart-Watches",
      //     brand: "Xiaomi",
      //   },
      //   {
      //     routes: "samsung-watch?limit=100",
      //     category: "Smart-Watches",
      //     brand: "Samsung",
      //   },
      //   {
      //     routes: "apple-bluetooth?limit=100",
      //     category: "Wireless-Earbuds",
      //     brand: "Apple",
      //   },
      {
        routes: "nokia-mobiles",
        category: "Mobiles",
        brand: "Nokia",
      },
      // {
      //   routes: "samsung-mobiles",
      //   category: "Mobiles",
      //   brand: "Samsung",
      // },
      //   {
      //     routes: "samsung-tablets",
      //     category: "Tablets",
      //     brand: "Samsung",
      //   },
      //   {
      //     routes: "Realme-mobiles",
      //     category: "Mobiles",
      //     brand: "Realme",
      //   },
      //   {
      //     routes: "Infinix-mobiles",
      //     category: "Mobiles",
      //     brand: "Infinix",
      //   },
      // {
      //   routes: "Oppo-mobiles",
      //   category: "Mobiles",
      //   brand: "Oppo",
      // },
      // {
      //   routes: "Tecno-mobiles",
      //   category: "Mobiles",
      //   brand: "Tecno",
      // },
      // {
      //   routes: "Vivo-mobiles",
      //   category: "Mobiles",
      //   brand: "Vivo",
      // },
      //   {
      //     routes: "Nokia-mobiles-price-in-pakistan?limit=100",
      //     category: "Mobiles",
      //     brand: "Nokia",
      //   },
      //   {
      //     routes: "Mi-Xiaomi-mobile-price-in-pakistan?limit=100",
      //     category: "Mobiles",
      //     brand: "Xiaomi",
      //   },
      //   {
      //     routes: "Apple-iPads-Prices-in-Pakistan?limit=100",
      //     category: "Mobiles",
      //     brand: "Apple",
      //   },
    ],
  },
];
