exports.arrayOfStores = [
  {
    storeName: "priceoye.pk",
    classNames: ".innerp.product-box",
    arrayOfRoutes: [
      "mobiles/apple",
      "mobiles/samsung",
      "mobiles/oppo",
      "mobiles/realme",
      "mobiles/infinix",
      "mobiles/tecno",
      "mobiles/vivo",
      "mobiles/xiaomi",
      "tablets/apple",
      "tablets/samsung",
      "tablets/huawei",
      "tablets/deny",
      "smart-watches/apple",
      "smart-watches/huawei",
      "smart-watches/samsung",
      "smart-watches/huawei",
      "smart-watches/xiaomi",
      "wireless-earbuds/anker",
      "wireless-earbuds/baseus",
      "wireless-earbuds/ronin",
      "wireless-earbuds/apple",
      "wireless-earbuds/huawei",
      "wireless-earbuds/samsung",
      "wireless-earbuds/huawei",
      "wireless-earbuds/xiaomi",
      "laptops/apple",
      "laptops/hp",
      "laptops/dell",
      "laptops/lenovo",
    ],
  },
];
