exports.arrayOfStores = [
  // {
  //   storeName: "priceoye.pk",
  //   mainContainer: ".productBox.b-productBox",
  //   imgTag: "amp-img",
  //   detailBoxClasses: {
  //     proDetailBox: "#product-summary",
  //     name: "h3",
  //     price: ".summary-price.text-black.price-size-lg.bold",
  //     stock: ".summary-price.text-black.bold.stock-status",
  //     rating: ".semi-bold.rating-points",
  //   },
  //   arrayOfRoutes: [
  //     { routes: "mobiles/apple", category: "Mobiles" },
  // { routes: "mobiles/samsung", category: "Mobiles" },
  // { routes: "mobiles/oppo", category: "Mobiles" },
  // { routes: "mobiles/realme", category: "Mobiles" },
  // { routes: "mobiles/infinix", category: "Mobiles" },
  // { routes: "mobiles/tecno", category: "Mobiles" },
  // { routes: "mobiles/vivo", category: "Mobiles" },
  // { routes: "mobiles/xiaomi", category: "Mobiles" },
  // { routes: "tablets/apple", category: "Tablets" },
  // { routes: "tablets/samsung", category: "Tablets" },
  // { routes: "tablets/huawei", category: "Tablets" },
  // { routes: "tablets/deny", category: "Tablets" },
  // { routes: "smart-watches/apple", category: "Smart-Watches" },
  // { routes: "smart-watches/huawei", category: "Smart-Watches" },
  // { routes: "smart-watches/samsung", category: "Smart-Watches" },
  // { routes: "smart-watches/huawei", category: "Smart-Watches" },
  // { routes: "smart-watches/xiaomi", category: "Smart-Watches" },
  // { routes: "wireless-earbuds/anker", category: "Wireless-Earbuds" },
  // { routes: "wireless-earbuds/baseus", category: "Wireless-Earbuds" },
  // { routes: "wireless-earbuds/ronin", category: "Wireless-Earbuds" },
  // { routes: "wireless-earbuds/apple", category: "Wireless-Earbuds" },
  // { routes: "wireless-earbuds/huawei", category: "Wireless-Earbuds" },
  // { routes: "wireless-earbuds/samsung", category: "Wireless-Earbuds" },
  // { routes: "wireless-earbuds/huawei", category: "Wireless-Earbuds" },
  // { routes: "wireless-earbuds/xiaomi", category: "Wireless-Earbuds" },
  // { routes: "laptops/apple", category: "Laptops" },
  // { routes: "laptops/hp", category: "Laptops" },
  // { routes: "laptops/dell", category: "Laptops" },
  // { routes: "laptops/lenovo", category: "Laptops" },
  // ],
  // },
  {
    storeName: "qmart.pk",
    // mainContainer: ".main-products.product-grid",
    mainContainer: ".product-layout",
    imgTag: "img",
    detailBoxClasses: {
      proDetailBox: "#product-summary",
      name: "h3",
      price: ".summary-price.text-black.price-size-lg.bold",
      stock: ".summary-price.text-black.bold.stock-status",
      rating: ".semi-bold.rating-points",
    },
    arrayOfRoutes: [
      { routes: "iPhone-price-in-pakistan", category: "Mobiles" },
      // { routes: "mobiles/samsung", category: "Mobiles" },
      // { routes: "mobiles/oppo", category: "Mobiles" },
      // { routes: "mobiles/realme", category: "Mobiles" },
      // { routes: "mobiles/infinix", category: "Mobiles" },
      // { routes: "mobiles/tecno", category: "Mobiles" },
      // { routes: "mobiles/vivo", category: "Mobiles" },
      // { routes: "mobiles/xiaomi", category: "Mobiles" },
      // { routes: "tablets/apple", category: "Tablets" },
      // { routes: "tablets/samsung", category: "Tablets" },
      // { routes: "tablets/huawei", category: "Tablets" },
      // { routes: "tablets/deny", category: "Tablets" },
      // { routes: "smart-watches/apple", category: "Smart-Watches" },
      // { routes: "smart-watches/huawei", category: "Smart-Watches" },
      // { routes: "smart-watches/samsung", category: "Smart-Watches" },
      // { routes: "smart-watches/huawei", category: "Smart-Watches" },
      // { routes: "smart-watches/xiaomi", category: "Smart-Watches" },
      // { routes: "wireless-earbuds/anker", category: "Wireless-Earbuds" },
      // { routes: "wireless-earbuds/baseus", category: "Wireless-Earbuds" },
      // { routes: "wireless-earbuds/ronin", category: "Wireless-Earbuds" },
      // { routes: "wireless-earbuds/apple", category: "Wireless-Earbuds" },
      // { routes: "wireless-earbuds/huawei", category: "Wireless-Earbuds" },
      // { routes: "wireless-earbuds/samsung", category: "Wireless-Earbuds" },
      // { routes: "wireless-earbuds/huawei", category: "Wireless-Earbuds" },
      // { routes: "wireless-earbuds/xiaomi", category: "Wireless-Earbuds" },
      // { routes: "laptops/apple", category: "Laptops" },
      // { routes: "laptops/hp", category: "Laptops" },
      // { routes: "laptops/dell", category: "Laptops" },
      // { routes: "laptops/lenovo", category: "Laptops" },
    ],
  },
];
